# Generated by Django 2.0.7 on 2018-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('judge_file', models.FileField(upload_to='judge/')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.Assignment'),
        ),
    ]
