# Generated by Django 2.0.7 on 2018-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='score'),
        ),
    ]
