# Generated by Django 2.0.7 on 2018-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
